### ISSUE TITLE
Not hearing any swing sounds or hit sounds (only tested wood fists)

### ISSUE THREAD

**Issue by br8k** [ceko/valheim-brawler#2]
The unarmed fists have a swoosh when you swing and a thud when you hit something, but I tried the Wood Sprig and it has neither. (Punching a tree gets you the impact sound of the tree being hit, but you should also hear the particular impact sound from the fist, like with unarmed. Punching a rock is completely silent. And whether punching something or swinging at air, there ought to be that "swoosh" noise that the unarmed fists have.)

(edit: I also just tested the Iron Cestus with the same result.)

**Comment by ceko** [comment]
Fixed in 0.0.4
