### ISSUE TITLE
Trying to pick this up having issues with your unity project

### ISSUE THREAD

**Issue by sbtoonz** [ceko/valheim-brawler#6]
Not sure why it fails to resolve refs to your scriptables that seem to exist or is this meant to be imported ontop of a utiny rip?
was curious if you had a working unity folder for the mod still and if  you would be willing to show me your prefab layout (I can look at the prefabs as well in text and just look for m_** thing) 

Will poke more at that today love this concept think its very achievable with the new libs to support mods for Valheim

**Comment by ceko** [comment]
Are you having issues opening the Unity project? I dragged in Valheim DLL references inside Unity (the publicized ones are probably fine). I just didn't want to include them in the repo.

**Comment by sbtoonz** [comment]
all good that answers your deployment method of unity 

I will fix my project and get these going :D 

thanks

**Comment by sbtoonz** [comment]
Hey was curious 

Would you prefer a PR with updated code? I wanted to be able to have an update to this weapon kit as it is AMAZING 

I got them all going in Jotunn no problem with stats / pics / everything as you setup initially 

AMAZING work on the 3d models etc 

Wasn't sure if you had abandoned this project or not 

If it is abandonware let me know I think others would enjoy an update to your mod as well :D

**Comment by ceko** [comment]
I'm good, it's abandonware along with the armor stand. I just wanted to try to make something cool, but I don't have the drive to maintain it or much interest in Valheim anymore.

Feel free to take and modify as needed. If you're uncomfortable with the license I can change it, but it should effectively be completely free and open to you unless you're trying to sell it.

The black metal tier model is a little janky, I never combined it into one mesh. But thanks for the compliment.
